### ISSUE TITLE
Tekton Docs Versioning

### ISSUE THREAD

**Issue by jerop** [tektoncd/website#197]
### Feature
The Tekton documentation in [tekton.dev](https://tekton.dev/) does not contain the versions of documentation from different Tekton projects releases. [Versioned docs are required for Pipelines GA](https://docs.google.com/document/d/1M0bO-0ZhJanV0a0cweSoR0RHdVw2Alt7XAEPaqdULc4/edit#) so that users can easily discover and use documentation from different releases. Currently, Tekton projects maintain versioned docs tables in their readme ([example in Pipelines](https://github.com/tektoncd/pipeline#read-the-docs)). 

### Requirements
- Documentation should be easily discoverable in both the [repositories](https://github.com/tektoncd) and in [tekton.dev](https://tekton.dev/)
- Support versioned documentation for different Tekton projects (pipelines, triggers, etc), that is, each project’s documentation should have a version selector
- Prominently display the current documentation version for each project
- Default to the latest stable version for each project
- Users should be able to select any version of all the Tekton projects 
- Older versions should have a banner warning that it’s an older version, with a link to the latest stable version

### Related
- [Original Doc](https://docs.google.com/document/d/1_ud3WEUQwlCif4fKgFdU4Uo5SY0EukZpwu0XHTMEV3Q/edit#)
- https://github.com/tektoncd/website/issues/130
- https://github.com/tektoncd/pipeline/pull/2836
- [Docs Project Decoupling](https://docs.google.com/document/d/1OtXWyYDiUV_5Sy8VfUqDIopBYQI3gPeTh6FyMZV1zvI/edit#)

/kind feature
/cc @sergetron @vdemeester @popcor255 @bobcatfish

**Comment by afrittoli** [comment]
Thanks for reporting this!
Some of it is already solved, I'll put more comments inline.


> ### Feature
> The Tekton documentation in [tekton.dev](https://tekton.dev/) does not contain the versions of documentation from different Tekton projects releases. 

It does now! 🎉 

> [Versioned docs are required for Pipelines GA](https://docs.google.com/document/d/1M0bO-0ZhJanV0a0cweSoR0RHdVw2Alt7XAEPaqdULc4/edit#) so that users can easily discover and use documentation from different releases. Currently, Tekton projects maintain versioned docs tables in their readme ([example in Pipelines](https://github.com/tektoncd/pipeline#read-the-docs)).

I think it's probably fine to keep the table in the main README, we could automate the creation of the table if needed.

> 
> ### Requirements
> * Documentation should be easily discoverable in both the [repositories](https://github.com/tektoncd) and in [tekton.dev](https://tekton.dev/)

Do you see anything missing on this side?

> * Support versioned documentation for different Tekton projects (pipelines, triggers, etc), that is, each project’s documentation should have a version selector

Right now they're combined in one dropdown, but it is possible to select the version of each project independently. Navigation includes docs from all projects only when the latest version for all is selected.

> * Prominently display the current documentation version for each project

This is done in the dropdown, but we could have this elsewhere too.

> * Default to the latest stable version for each project

This is the current behaviour. It relies on the version being configured correctly in the `sync.yaml`.  We have add/remove version scripts to help maintain that configuration when a new release is created.

> * Users should be able to select any version of all the Tekton projects

Currently we only have 4 + master configured. 
It is technically possibly to configure all versions, however the versions dropdown would become too long, so the design of that dropdown would have to be revised.

> * Older versions should have a banner warning that it’s an older version, with a link to the latest stable version

There is a feature in the docsy template for this, I believe it will display the banner on every version but the most recent. I'm not sure though if the website is setup so that we could benefit from the setting on docsy.

> 
> ### Related
> * [Original Doc](https://docs.google.com/document/d/1_ud3WEUQwlCif4fKgFdU4Uo5SY0EukZpwu0XHTMEV3Q/edit#)
> * #130
> * [tektoncd/pipeline#2836](https://github.com/tektoncd/pipeline/pull/2836)
> * [Docs Project Decoupling](https://docs.google.com/document/d/1OtXWyYDiUV_5Sy8VfUqDIopBYQI3gPeTh6FyMZV1zvI/edit#)
> 
> /kind feature
> /cc @sergetron @vdemeester @popcor255 @bobcatfish
