### ISSUE TITLE
Translation of Tekton home page

### ISSUE THREAD

**Issue by takoh-yuuichiro** [tektoncd/website#243]
I would like to contribute to the project by translating the documents on the [Tekton home page](https://tekton.dev/) into Japanese.
For this purpose, I would like to confirm something:
- Is translation into Japanese meaningful?
- Are there any significant changes in the Tekton home page specifications?
Tekton's specifications have changed so often in the past that I'm worried that the translation and implementation will be a waste of time because of Tekton's specifications' changes.

I will be grateful for any help you can provide.

**Comment by jhonmike** [comment]
Hello @takoh-yuuichiro, I tried to translate the home page into brazilian portuguese and fall into some problems in the structure of the site, and due to lack of time I couldn't complete the process, but there are many pages that will have their content duplicated, so I can leave that content depreciated in our native languages ​​if English gets updated

my PR https://github.com/tektoncd/website/pull/198

But I also have the same doubts that you

**Comment by takoh-yuuichiro** [comment]
Hello @afrittoli , is translation into Japanese still meaningful?
I'm worried that the translation would be a waste of time due to changes to the website's specification.

Thanks

**Comment by kobaji** [comment]
Thanks @jhonmike for your kind information.
This is @kobaji , working with @takoh-yuuichiro .
#165 , the issue you opened is also interesting for me. I would be very grateful if your and takoh-san's contributions are meaningful even now.

**Comment by afrittoli** [comment]
https://github.com/tektoncd/website/pull/266#issuecomment-959781103

**Comment by afrittoli** [comment]
Thank you @takoh-yuuichiro for this issue. Based on @AlanGreene comments in https://github.com/tektoncd/website/pull/266#issuecomment-959781103 I would propose to close this issue for now.

**Comment by takoh-yuuichiro** [comment]
Thank you @afrittoli for sending us [#266 (comment)](https://github.com/tektoncd/website/pull/266#issuecomment-959781103) . We understand the comments. So closing this issue for now.
