### ISSUE TITLE
Automatically add an editorial reviewer team to every PR that modifies docs

### ISSUE THREAD

**Issue by sergetron** [tektoncd/website#252]
### Feature request

To maintain a high quality level for Tekton documentation, documentation changes should go through editorial review in addition to technical review. @Sergetron and other members of the Tekton Docs Working Group are willing to volunteer as editorial reviewers. The best way to make this happen is to automatically add the editorial reviewers to every PR that modifies documentation.

### Use case

Prerequisites: We must create a GitHub team that includes Tekton docs reviewers.

1. Someone creates a PR against any of the Tekton project repos and that PR contains documentation changes.
2. When we detect that the PR contains changes to files in the /docs directory, we automatically add the docs reviewers team as reviewers for the PR.
3. PR goes through normal review process with docs changes reviewed for technical accuracy by the usual reviewers and for language, structure, and other editorial items by the docs reviewers team.

**Comment by afrittoli** [comment]
This will be implemented as follows:
- create a tekton task or pipeline that will run on PR open/reopen/sync/label, with the following logic
- check if the label `kind/documentation` is set or if any file in the docs folder is modified or any `*.md` file is modified
- in case of match cc the @tektoncd/docs-reviewers team on the PR

**Comment by afrittoli** [comment]
I've been trying to implement this by requesting the doc team as a reviewer on PRs, however it turns out that only repo collaborators can be reviewers (from GitHub point of view). Making the doc reviewers team a collaborator of all repos would automatically git `/lgtm` powers to all members of the team on all repos, which is not what we want.
The only alternative I can think of is to add a comment to the PR with @tektoncd/docs-reviewers - that should trigger a notification email, so it should be enough.

**Comment by sergetron** [comment]
Thank you for investigating this Andrea. I think the email notification works, this way at least we're aware that there are docs changes being made.

**Comment by afrittoli** [comment]
Once the catalog update is done, it'll be quick to add to the CI job.
