### ISSUE TITLE
Picture/Diagram missing on Documentation page Triggers and EventListeners

### ISSUE THREAD

**Issue by vovtz** [tektoncd/website#340]
# Expected Behavior
All images/diagrams in the documentation are present

# Actual Behavior
The SVG image about the Trigger Flow does not exist (shows a broken image icon) on the Triggers and EventListeners page

# Steps to Reproduce the Problem

1. Open https://tekton.dev/docs/triggers/ in a browser
2.
3.

# Additional Info
The SVG images URL is https://tekton.dev/docs/images/TriggerFlow.svg

**Comment by AlanGreene** [comment]
@tektoncd/triggers-maintainers fyi

**Comment by afrittoli** [comment]
I looked a bit at this one, and the problem is that the image is not stored along with the docs, but in an `images` folder, which is a peer of the `docs` one. I suspect the easiest fix here would be to move the image around, possibly place the `images` folder under `docs` in the `triggers` repo would help already.

Alternatively we could add logic to the sync script to handle shared images, e.g.:

- each project could specify one shared images folder
- those images could be copied into the hugo static content folder, in a project/version specific subfolder
- links to the image would be overwritten accordingly

This would quite a bit of engineering to be done for a feature that I'm not convinced we need.

**Comment by AlanGreene** [comment]
I'd be in favour of the easier approach here:
> I suspect the easiest fix here would be to move the image around, possibly place the images folder under docs in the triggers repo would help already.

**Comment by khrm** [comment]
Sure, I would move the images folder under docs folder.

**Comment by vovtz** [comment]
Thanks for the fast resolution. When will this result in a change of the effected website page (https://tekton.dev/docs/triggers/)?

**Comment by khrm** [comment]
@afrittoli I think placing `images` folder inside triggers `docs` folders didn't solve this. Or is the website yet to be rebuilt?

**Comment by afrittoli** [comment]
Thanks @khrm I need to update the website config to include the new folder. 
Once I've done that it should on the "main" branch docs. If you want to fix it on the docs associated to a release you'll need to backport the fix to the branch

**Comment by AlanGreene** [comment]
This came up during the Docs WG today when reviewing potential issues for new contributors.

@afrittoli I see you have a PR open for this already: https://github.com/tektoncd/website/pull/351

Does it still require more work? If so, do you think you'll have bandwidth to work on it or does it need a new owner?

**Comment by vovtz** [comment]
/remove-lifecycle stale

Still looks like:

![image](https://user-images.githubusercontent.com/1536228/181715389-e0b625af-09f3-4e92-8b9c-01e8b547ad3b.png)

**Comment by vovtz** [comment]
The <img/> tag references https://tekton.dev/docs/triggers/images/TriggerFlow.svg, which doesn’t exist.
