### ISSUE TITLE
Make "search this site" work or remove it

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/website#42]
# Expected Behavior

I don't really know how "search this site" should work but i think it should only return results from this site?

# Actual Behavior

When I try searching for "tutorial" I get this:

![image](https://user-images.githubusercontent.com/432502/77015679-df6abf00-694b-11ea-8dfc-8e1da870032b.png)

# Additional Info

Maybe it's hard coded to search tekton.dev, in which case we probably need to update the search logic to use a netlify environment variable to search the preview site.

**Comment by tragiclifestories** [comment]
Putting this here as I expect it's the same issue.

# Expected Behavior

When I search for "trigger templates" on tekton.dev, I should get a link to the relevant page of the triggers docs.

# Actual Behavior

I get tonnes of results from prow builds and so on.

<img width="1185" alt="Screenshot 2020-04-15 at 10 44 30" src="https://user-images.githubusercontent.com/2285130/79323845-a69c1680-7f06-11ea-8ece-04310cf62f34.png">


# Steps to Reproduce the Problem

1. search for any piece of documentation
2. there will be no results from the documentation site, but you may get results from various subdomains of tekton dev.

# Additional Info

This does not seem to be something that can be fixed in code by J. Random Contributor, unfortunately. I'm guessing it's a Google Custom Search misconfiguration of some kind?

**Comment by popcor255** [comment]
@bobcatfish Can we implement a toggle for the search? Can we just conditionally render the search bar based on version-switcher.js?
