### ISSUE TITLE
Supply Chain Security - Getting Started

### ISSUE THREAD

**Issue by michaelsatish** [tektoncd/website#424]
# Expected Behavior
The word "TaskRuns" on the first bullet point under the **Current features include** section lacks highlights. The whole word should be highlighted. 

Signing `TaskRun` results with user provided cryptographic keys, including `TaskRuns` themselves and OCI Images

# Actual Behavior

Signing `TaskRun` results with user provided cryptographic keys, including `TaskRun`s themselves and OCI Images.

The alphabet "s" is missed out from the highlights.

# Steps to Reproduce the Problem

1. Visit "https://tekton.dev/docs/chains/#getting-started"

**Comment by AlanGreene** [comment]
I believe this is intentional as `TaskRun` is the kind that's being referenced. However, we do appear to have some inconsistency across the docs, with some content using `TaskRun`s and other `TaskRuns`.

@geriom fyi

**Comment by geriom** [comment]
I think this was already changed on the corresponding repo.

Something worth mentioning is that we are following [Kubernetes guidelines](https://kubernetes.io/docs/contribute/style/style-guide/#use-upper-camel-case-for-api-objects) in this regard, namely use upper camel case for API objects and do not use code style unless it specifically referring to code or file names.

So I that case it should be TaskRuns instead of `TaksRun`s. I'm going to do a major review of the Chains documentation and maybe move some content around next month.
