### ISSUE TITLE
docs navigation bug

### ISSUE THREAD

**Issue by Arhell** [tektoncd/website#427]
# Expected Behavior
![Screenshot_2](https://user-images.githubusercontent.com/26163841/186406877-cfac00f5-ae78-4fdc-a218-4876f22bf8f9.png)

# Actual Behavior
![Screenshot_1](https://user-images.githubusercontent.com/26163841/186406816-c109435d-d9a8-4202-97ae-4721ae405dc2.png)

# Steps to Reproduce the Problem

1. https://tekton.dev/docs/

/assign

**Comment by AlanGreene** [comment]
Thanks for raising the issue @Arhell. Can you clarify what the problem is that you're seeing?

Is it the angle of the arrow icon? If so, that is the hover state for the navigation. When you mouseover an item in the list the arrow rotates 30 degrees. It animates between its states, including when expanding and collapsing the nav items.

**Comment by Arhell** [comment]
> Thanks for raising the issue @Arhell. Can you clarify what the problem is that you're seeing?
> 
> Is it the angle of the arrow icon? If so, that is the hover state for the navigation. When you mouseover an item in the list the arrow rotates 30 degrees. It animates between its states, including when expanding and collapsing the nav items.

When hovering, it should turn down or not turn at all. I'll fix it soon, it doesn't look good
