### ISSUE TITLE
Additional Configuration Options: The file /docs/Pipelines/additional-configs.md was not found.

### ISSUE THREAD

**Issue by Abirdcfly** [tektoncd/website#513]
"The file /docs/Pipelines/additional-configs.md was not found."

https://tekton.dev/docs/installation/additional-configs/

![CleanShot 2023-02-13 at 14 20 09](https://user-images.githubusercontent.com/5100555/218385259-985882d5-abd2-43fe-98de-d4cad6e1c783.png)

**Comment by AlanGreene** [comment]
Thanks for raising this @Abirdcfly. Looks like this file was added since the most recent Pipelines release so is not being included.
While we resolve this you can find the content on GitHub at https://github.com/tektoncd/pipeline/blob/main/docs/additional-configs.md

@geriom Looks like this additional-configs.md file was added to the pipeline repo since the last release so it's not currently synced to the website. Do we want to back-port this to the v0.44 release branch?

Do we have a plan for versioning these docs (and other similar ones using `readfile`, e.g. vendor-specific content) or should they always reflect the latest release?

**Comment by geriom** [comment]
It's visible here: https://tekton.dev/vault/pipelines-main/additional-configs/

> @geriom Looks like this additional-configs.md file was added to the pipeline repo since the last release so it's not currently synced to the website. Do we want to back-port this to the v0.44 release branch?

What I was thinking is building the site docs from HEAD, then add a visible note with a links to the latest release and the latest LTS release. What do you think?

> Do we have a plan for versioning these docs (and other similar ones using `readfile`, vendor-specific content, etc.) or should they always reflect the latest release?

We have briefly discussed  versioning the website docs and version-specific docs, with no definitive decisions. I'll bring this up in the team meeting, write up a proposal, and share it with a wider audience for discussion.

**Comment by AlanGreene** [comment]
Docs have been updated and the link now works as expected. Thanks again @Abirdcfly
