### ISSUE TITLE
Getting started with Tasks (Kubernetes version incorrect)

### ISSUE THREAD

**Issue by yzaazy** [tektoncd/website#607]
https://tekton.dev/docs/getting-started/tasks/

When following the instruction and staring Minikube with "--kubernetes-version v1.25.14" it gives errors when installing Tekton pipelines pods. They get the status CrashLoopBackOff.

Starting Minikube with with "--kubernetes-version v1.30.0" resolves these problems.

**Comment by AlanGreene** [comment]
Thanks for reporting this @yzaazy. The minimum Kubernetes version required since Tekton Pipelines v0.59 is 1.27: https://github.com/tektoncd/pipeline/releases/tag/v0.59.0

Would you be interested in submitting a PR to update the minikube start command at https://github.com/tektoncd/website/blob/main/content/en/docs/Getting-started/tasks.md ?

**Comment by AlanGreene** [comment]
PR opened: https://github.com/tektoncd/website/pull/616
